services:
  flask:
    build:
      context: ./flask
    ports:
      - "5000:5000"
    volumes:
      - ./flask/app:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
